services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    image: notifications_fastapi
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
    
  notifications:
    image: notifications_fastapi
    depends_on:
      - rabbitmq
    volumes:
      - ./app/notifications.py:/code/app/notifications.py
    working_dir: /code
    #entrypoint: ["tail", "-f", "/dev/null"]
    entrypoint: ["python", "app/notifications.py"]

  postgres:
    image: postgres:13
    environment:
      # TODO: Change the password and save it in a secure place
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # TODO: create a volume for the database
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  

# To start the docker service
#   sudo service docker start
# To check the running processes
#   docker compose ps
# To Build the compose.yaml file and run the docker compose in the background
#   sudo docker compose up --detach --build
# To stop the running process
#   sudo docker compose down
# To check the logs of the running process
#   sudo docker compose logs -f
# To connect to the running container
#   sudo docker compose exec fastapi bash